### ISSUE TITLE
LoadBalancer

### ISSUE THREAD

**Issue by sagarkrkv** [airavata-courses/spring17-API-Server#3]

**Comment by sagarkrkv** [comment]
@anujbhan I have edited [userdata.sh](https://github.com/airavata-courses/spring17-API-Server/blob/loadBalancer/build-scripts/userdata.sh) to start consul and fabio. 

Can you run this on the dedicated instance?

**Comment by anujbhan** [comment]
yes, looking into it

**Comment by anujbhan** [comment]
setup is done
